"""empty message

Revision ID: 18cd2968cc3a
Revises: 40beeb5818f7
Create Date: 2021-12-28 18:14:26.170544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cd2968cc3a'
down_revision = '40beeb5818f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_listings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('cart_listings', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_listings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart_listings', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_listings', type_='foreignkey')
    op.drop_constraint(None, 'cart_listings', type_='foreignkey')
    op.drop_column('cart_listings', 'listing_id')
    op.drop_column('cart_listings', 'user_id')
    # ### end Alembic commands ###
