"""empty message

Revision ID: 9d72ef5a65ad
Revises: ebdd8e5e5dd1
Create Date: 2021-12-28 16:58:59.760051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d72ef5a65ad'
down_revision = 'ebdd8e5e5dd1'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
