"""edit-tags

Revision ID: 6a4a63873685
Revises: f5f32a0359ac
Create Date: 2021-12-23 11:20:24.288222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4a63873685'
down_revision = 'f5f32a0359ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'action',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'adventure',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'rpg',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'mmo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'casual',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'sports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'simulation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'strategy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'racing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'rts',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'horror',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'platformer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'platformer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'horror',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'rts',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'racing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'strategy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'simulation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'sports',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'casual',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'mmo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'rpg',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'adventure',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'action',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
