"""tags

Revision ID: f5f32a0359ac
Revises: 29671d9786a4
Create Date: 2021-12-23 11:08:45.337576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f32a0359ac'
down_revision = '29671d9786a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.Boolean(), nullable=False),
                    sa.Column('adventure', sa.Boolean(), nullable=False),
                    sa.Column('rpg', sa.Boolean(), nullable=False),
                    sa.Column('mmo', sa.Boolean(), nullable=False),
                    sa.Column('casual', sa.Boolean(), nullable=False),
                    sa.Column('sports', sa.Boolean(), nullable=False),
                    sa.Column('simulation', sa.Boolean(), nullable=False),
                    sa.Column('strategy', sa.Boolean(), nullable=False),
                    sa.Column('racing', sa.Boolean(), nullable=False),
                    sa.Column('rts', sa.Boolean(), nullable=False),
                    sa.Column('horror', sa.Boolean(), nullable=False),
                    sa.Column('platformer', sa.Boolean(), nullable=False),
                    sa.Column('listing_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('listings_name_key', 'listings', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('listings_name_key', 'listings', ['name'])
    op.drop_table('tags')
    # ### end Alembic commands ###
