"""refactored reviews

Revision ID: e0f4c6a9355b
Revises: e293002f816a
Create Date: 2021-12-28 12:52:02.347747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f4c6a9355b'
down_revision = 'e293002f816a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dislikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'review_id')
    )
    op.drop_column('reviews', 'likes')
    op.drop_column('reviews', 'dislikes')
    op.drop_column('user_likes', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_likes', sa.Column('likes', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('user_dislikes')
    # ### end Alembic commands ###
