"""updated listings

Revision ID: 42dd79b10bff
Revises: b089ac5f4dfd
Create Date: 2021-12-16 13:28:48.209590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dd79b10bff'
down_revision = 'b089ac5f4dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'price')
    # ### end Alembic commands ###
