"""Initial migration.

Revision ID: fad65fb08fe1
Revises: 9d72ef5a65ad
Create Date: 2021-12-28 18:04:45.940623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad65fb08fe1'
down_revision = '9d72ef5a65ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_listings',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('listing_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_listings')
    # ### end Alembic commands ###
